version: '3.6'

services:

  web:
    image: nginx
    restart: always
    volumes:
      - ./share:/usr/share/nginx/html
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=0.0.0.0

#http://localhost:8080/?pgsql=db&username=empose&db=empose&ns=public
